### ISSUE TITLE
Abstract Syntax Tree crashes when use SELECT FOR UPDATE

### ISSUE THREAD

**Issue by machadowelton** [felipebz/zpa#137]
I’m make the custom rules to PLSQL analysis and am using the sslr-plsql-toolkit-3.4.1.2576.jar to guide me to find violated rules in the code blocks.

So when i parse code with a simple SELECT the Abstract Syntax Tree is mapped correcly:

```sql
CREATE OR REPLACE PACKAGE BODY package_sample_sonar_rules AS
	PROCEDURE rule21_compliant
	IS
	VAR1 INTEGER := 10;
	CURSOR cursor1 IS
		SELECT 
			col1,
			col2
		FROM
			tab1
		WHERE col1 > VAR1;
	BEGIN
		OPEN cursor1;
		CLOSE cursor1;		
	END rule21_compliant;
END package_sample_sonar_rules;
/
```
![cp1](https://user-images.githubusercontent.com/5694291/78245711-51034b00-74be-11ea-95b8-c435a90b82bb.png)

But i need find the SELECT WITH FOR UPDATE on code Because my rules do not allow the use of FOR UPDATE. So when add FOR UPDATE  on SELECT, the Abstract Syntax Tree crashes and the SELECT on the tree is not similar to SELECT without FOR UPDATE

```sql
CREATE OR REPLACE PACKAGE BODY package_sample_sonar_rules AS
	PROCEDURE rule21_compliant
	IS
	VAR1 INTEGER := 10;
	CURSOR cursor1 IS
		SELECT 
			col1,
			col2
		FROM
			tab1
		WHERE col1 > VAR1 FOR UPDATE;
	BEGIN
		OPEN cursor1;
		CLOSE cursor1;		
	END rule21_compliant;
END package_sample_sonar_rules;
/
```
![cp2](https://user-images.githubusercontent.com/5694291/78245737-5d87a380-74be-11ea-95e2-82c47170ce0f.png)

**Comment by felipebz** [comment]
Hi again. :-) (Yes, I'm the same person that answered you [here](https://community.sonarsource.com/t/abstract-syntax-tree-crashes-when-use-select-for-update/22489/2?u=felipebz))

Unfortunately you're using the commercial plugin from SonarSource and you'll need to ask them to fix [this bug](https://jira.sonarsource.com/browse/SONARPLSQL-201), but as you can see they know about this problem since 2012 and didn't fixed it yet. I wouldn't expect a fix soon.

However if you're willing to migrate to [my plugin](https://github.com/felipebz/zpa#installation) I could help you. I know I'm biased but I think it has a better parser than the one from the SonarSource analyzer. ;-) You can test my parser using the [zpa-toolkit](https://github.com/felipebz/zpa/releases/download/2.4.0/zpa-toolkit-2.4.0.jar).

![image](https://user-images.githubusercontent.com/13829/78247481-4dbd8e80-74c1-11ea-8a89-107cafdc63c8.png)

**Comment by machadowelton** [comment]
@felipebz is possible use the comercial plugin and your plugin on server?

**Comment by felipebz** [comment]
@machadowelton you can install both plugins in the same server, but you can't run both analyzers at the same time (in a single analysis). See issue #133.
