### ISSUE TITLE
Why is SonarLint support disabled?

### ISSUE THREAD

**Issue by l0wlik34G6** [felipebz/zpa#140]
Is there a reason why sonarLint support is inactive?

https://github.com/felipebz/zpa/blob/master/sonar-plsql-open-plugin/pom.xml
`<sonarLintSupported>false</sonarLintSupported>`

It would be helpful to have it true, for e.g. using linting in vscode or any other IDE where a linter is used.

PS: Sorry I didn't find any other place where I could ask such question.

**Comment by felipebz** [comment]
Unfortunately, SonarLint doesn't support third-party analyzers. Even if we set this property to 'true", SonarLint won't load this plugin.

This is the explanation from a SonarSource employee: https://community.sonarsource.com/t/is-it-possible-to-add-a-placeholder-for-loading-customize-plugin-for-language-not-supported-in-sonarlint/27123/2

**Comment by l0wlik34G6** [comment]
Sorry for the late reaction.

I wrote a linter for Sublime and it only works if sonarLintSupported is set to true.
However, I changed it by making a change in the sonarlint source.
Therefore I don't know if the change in the pom.xml would fix that.

If that's really the case this is very sad and kind of makes sonarlint pretty useless, but that's not topic of this repo.

Thanks for your efforts on PLSQL linting :)

**Comment by l0wlik34G6** [comment]
According to the documentation this is not true.

See https://docs.sonarqube.org/latest/extend/developing-plugin/
sonarLintSupported | SonarLint-Supported | Whether  the language plugin supports SonarLint or not. Only SonarSource  analyzers and custom rules plugins for SonarSource analyzers should set  this to true.
-- | -- | --

**Comment by felipebz** [comment]
I'm closing this issue because the only way to "fix" this limitation is forking SonarLint **or** extending the SonarSource's SonarPLSQL plugin (impllies in #133) and I don't have any plans to do it.

I hope to integrate ZPA with some IDEs using a "SonarLint-like" product ([ZPA CLI](https://github.com/felipebz/zpa-cli)), like [this proof of concept](https://github.com/felipebz/zpa-plsql-developer-plugin) which integrates with PL/SQL Developer from Allround Automations.
